Add PreLoadedPlugin mixin for pre-initialized plugins
vyuh-tech/vyuh pull request #19
Opened 2024-09-15 11:29 UTC by vishal-kr-barnwal

This will help us to mark any plugin to be preloaded without any Change to Vyuh Core.

Revamped the handling of preloaded plugins by introducing the PreLoadedPlugin mixin. Applied this mixin to DIPlugin, AnalyticsPlugin, and NetworkPlugin to ensure they are initialized before the platform. Removed the static list of preloadedPlugins from VyuhPlatform.

2024-09-15 14:06 UTC, pavanpodila requested changes

2024-09-15 14:06 UTC, pavanpodila commented on packages/system/vyuh_core/lib/plugin/plugin_descriptor.dart
> +class PluginDescriptor {
can be final

2024-09-15 14:06 UTC, pavanpodila commented on packages/system/vyuh_core/lib/runtime/platform/default_platform.dart
> +class _CacheableLookupPluginList {
just call it `_PluginInstanceCache`

2024-09-16 02:29 UTC, pavanpodila approved these changes
changes done

2024-09-16 02:31 UTC, vishal-kr-barnwal commented
Keeping it in draft, for few more chnages.

2024-09-18 05:03 UTC, pavanpodila approved these changes

2024-09-18 05:03 UTC, merged

2024-09-18 05:04 UTC, pavanpodila commented
Fixed the developer feature and also improved the ergonomics of PluginDescriptor