feat(sanity_client): add ability to post request
vyuh-tech/vyuh pull request #39
Opened 2024-12-14 08:28 UTC by stephenrichter

This PR adds the ability for the `sanity_client` to do `POST` requests with a GROQ query as the JSON body.

This avoids the issue where a GROQ query string is too long to use with http `GET`.

See https://www.sanity.io/docs/http-query#J0Wj7Tip for more information

2024-12-15 01:13 UTC, pavanpodila requested changes

2024-12-15 01:13 UTC, pavanpodila commented on packages/sanity/sanity_client/lib/url_builder.dart
> +  Uri postUrl() {
Why don't we do this with standard query itself by checking for size of the query string. If it's longer we could switch to post method automatically. That will simplify the usage as well. 

Thoughts?

2024-12-16 18:47 UTC, stephenrichter commented on packages/sanity/sanity_client/lib/url_builder.dart
> +  Uri postUrl() {
@pavanpodila I like this method better. I've added a `SanityRequest` class which handles the logic internally to determine whether the query `requiresPost` or not.

This means the API will remain the same `SanityClient.fetch()` and will do the magic behind the scenes 😉

2024-12-17 04:19 UTC, pavanpodila commented on packages/sanity/sanity_client/lib/client.dart
> +    );
Very nice approach with the request! and neatly captures the essence. I think we can make the SanityRequest private and use the part/part-of directives to ensure its not leaked outside.

Also can we add some tests to ensure coverage does not drop ?

2024-12-20 00:55 UTC, stephenrichter commented on packages/sanity/sanity_client/lib/client.dart
> +    );
It's not recommended to use part/part-of directives, so I've used a `lib/src` folder to maintain `SanityRequest` as private and not expose it with the library. See https://github.com/dart-lang/site-www/issues/2371 for more info.

I've also added test coverage to make sure the 11kb limit is respected and GET/POST are operating correctly.

2024-12-20 03:37 UTC, pavanpodila requested changes

2024-12-20 03:37 UTC, pavanpodila commented on packages/sanity/sanity_client/lib/url_builder.dart
> +  Uri postUrl() {
can we absorb this as well in the queryUrl() ... I think the choice of url construction is an implementation detail and should not be exposed outside..

2024-12-20 09:02 UTC, stephenrichter commented on packages/sanity/sanity_client/lib/url_builder.dart
> +  Uri postUrl() {
Makes sense. Done.

2024-12-20 10:11 UTC, pavanpodila approved these changes

2024-12-20 10:12 UTC, merged

2024-12-20 10:12 UTC, pavanpodila commented
Cool PR and implementation @stephenrichter 🥇

2024-12-20 10:12 UTC, pavanpodila commented
@all-contributors add @stephenrichter for code,docs,test